AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::LanguageExtensions'
Parameters:
  ImageID:
    Description: Image ID
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'
  Environment:
    Description: Environment tier
    Type: String

Mappings:
  Environments:
    stage:
      instanceSize: t2.micro
      secGroup: sg-03671d496c0855f89
    prod:
      instanceSize: t3.micro
      secGroup: sg-06db931a08e2a02cf

Resources:
  # AllowSSH:
  #   Type: AWS::EC2::SecurityGroup
  #   DeletionPolicy: Retain
  #   Properties:
  #     GroupName: !Sub allow-ssh-${Environment}
  #     GroupDescription: Allows SSH
  #     SecurityGroupIngress:
  #       - IpProtocol: tcp
  #         FromPort: 22
  #         ToPort: 22
  #         CidrIp: 82.102.114.179/32
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: A4L
      ImageId: !Ref ImageID
      InstanceType: !FindInMap [Environments, !Ref Environment, instanceSize]
      SecurityGroupIds:
        - !FindInMap [Environments, !Ref Environment, secGroup]
      UserData: !Base64 |
        #!/bin/bash -ex
        echo "It worked!" > /root/worked.txt
      Tags:
        - Key: Name
          Value: !Sub "SampleInstance-${Environment}"

Outputs:
  IpAddress:
    Value: !GetAtt Instance.PublicIp

